MemberShip/web/admin/app/views/apps.py
# -*- coding:utf-8 -*-

import os

from flask import Blueprint
from flask import render_template
from flask import abort
from flask import redirect
from flask import request
from flask import session
from flask import url_for
from flask import send_from_directory

from flask.ext.babel import gettext
from flask.ext.login import login_required

from config import ADMIN_UPLOAD_PATH as UPLOAD_PATH

from app import forms
from app import helpers
from app import models

from util import make_pagination


view = Blueprint('apps', __name__, 
                 template_folder='../templates')


@view.route('/')
@login_required
def apps():
    apps = models.apps()
    return render_template('apps/apps.html',
                           apps = apps)


@view.route('/<int:app_id>')
@login_required
def apps_detail(app_id):
    app = models.apps_detail(app_id)
    if not app:
        return abort(404)

    products = models.products(app_id)
    return render_template('apps/apps_detail.html',
                           app = app,
                           products = products)


@view.route('/new', methods=['POST', 'GET'])
@login_required
def apps_new():
    form = forms.AppForm()
    if form.validate_on_submit():
        models.apps_new(form)
        return redirect('/apps')

    form.app_id.data = models.auto_created()
    form.app_id.readonly = True
    form.app_key.data = models.auto_created()
    form.app_key.readonly = True
    form.app_secret.data = models.auto_created()
    form.app_secret.readonly = True
    form.facebook_api_version.choices = models.facebook_api_version_choices()
    form.status.choices = models.app_status_choices()
    
    return render_template('apps/apps_edit.html',
                           form = form, h = helpers)


@view.route('/edit/<int:app_id>', methods=['POST', 'GET'])
@login_required
def apps_edit(app_id):
    app = models.apps_detail(app_id)
    if not app:
        return abort(404)

    form = forms.AppForm()
    if form.validate_on_submit():
        models.apps_edit(form)
        return redirect('/apps')

    form.app_id.data = app['app_id']
    form.app_id.readonly = True
    form.app_key.data = app['app_key']
    form.app_key.readonly = True
    form.app_secret.data = app['app_secret']
    form.app_secret.readonly = True
    form.app_name.data = app['app_name']

    form.support_android.data = app['support_android']
    form.support_playstore.data = app['support_playstore']
    form.playstore_url.data = app['playstore_url']
    form.gcm_sender_id.data = app['gcm_sender_id']
    form.gcm_server_api_key.data = app['gcm_server_api_key']
    form.gcm_config_path.data = app['gcm_config_path']

    form.support_ios.data = app['support_ios']
    form.appstore_url.data = app['appstore_url']

    form.support_gameflier.data = app['support_gameflier']
    form.gameflier_url.data = app['gameflier_url']

    form.facebook_app_id.data = app['facebook_app_id']
    form.facebook_app_name.data = app['facebook_app_name']
    form.facebook_app_secret.data = app['facebook_app_secret']
    form.facebook_api_version.choices = models.facebook_api_version_choices()
    form.facebook_api_version.data = models.facebook_api_version_index(app['facebook_api_version'])

    form.status.choices = models.app_status_choices()
    form.status.data = models.app_status_index(app['status'])

    return render_template('apps/apps_edit.html',
                           form = form, h = helpers)


@view.route('/delete/<int:app_id>', methods=['POST', 'GET'])
@login_required
def apps_delete(app_id):
    models.apps_delete(app_id)
    return redirect('/apps')


@view.route('/file/<int:app_id>/<filename>')
@login_required
def apps_file(app_id, filename):
    upload_path = os.path.join(UPLOAD_PATH, str(app_id))
    return send_from_directory(upload_path, filename)



@view.route('/<int:app_id>/products')
@login_required
def products(app_id):
    products = models.products(app_id)
    return render_template('apps/products.html',
                           app_id = app_id,
                           products = products)


@view.route('/<int:app_id>/products/<int:product_id>')
@login_required
def products_detail(app_id, product_id):
    product = models.products_detail(app_id, product_id)
    if not product:
        abort(404)

    return render_template('apps/products_detail.html',
                           product = product)


@view.route('/<int:app_id>/products/new', methods=['POST', 'GET'])
@login_required
def products_new(app_id):
    form = forms.ProductForm()
    if form.validate_on_submit():
        models.products_new(form)
        return redirect('/apps/%d/products' % (app_id))

    form.app_id.data = app_id
    form.app_id.readonly = True
    form.product_id.data = models.auto_created()
    form.product_id.readonly = True
    form.service_platform.choices = models.service_platform_choices()
    form.currency.choices = models.currency_type_choices()
    form.status.choices = models.product_status_choices()

    return render_template('apps/products_edit.html',
                           app_id = app_id,
                           form = form, h = helpers)


@view.route('/<int:app_id>/products/edit/<int:product_id>', methods=['POST', 'GET'])
@login_required
def products_edit(app_id, product_id):
    product = models.products_detail(app_id, product_id)
    if not product:
        return abort(404)

    form = forms.ProductForm()
    if form.validate_on_submit():
        models.products_edit(form)
        return redirect('/apps/%d/products' % (app_id))

    form.app_id.data = product['app_id']
    form.app_id.readonly = True
    form.product_id.data = product['product_id']
    form.product_id.readonly = True
    form.product_name.data = product['product_name']
    form.product_detail.data = product['product_detail']
    form.product_price.data = product['product_price']
    form.inapp_id.data = product['inapp_id']
    form.service_platform.choices = models.service_platform_choices()
    form.service_platform.data = models.service_platform_index(product['service_platform'])
    form.currency.choices = models.currency_type_choices()
    form.currency.data = models.currency_type_index(product['currency'])
    form.status.choices = models.product_status_choices()
    form.status.data = models.product_status_index(product['status'])
    
    return render_template('apps/products_edit.html',
                           app_id = app_id,
                           form = form, h = helpers)


@view.route('/<int:app_id>/products/delete/<int:product_id>', methods=['POST', 'GET'])
@login_required
def products_delete(app_id, product_id):
    models.products_delete(app_id, product_id)
    return redirect('/apps/%d/products' % (app_id))


@view.route('/<int:app_id>/payments', defaults={'page':1})
@view.route('/<int:app_id>/payments/page=<int:page>')
@login_required
def payments(app_id, page):
    # 검색 조건 가져오기
    # TODO: 검색 조건 추가
    member_id = request.args.get('member_id', None)
    product_id = request.args.get('product_id', None)

    # 멤버 아이디로 검색
    if member_id:
        total, payments = models.payments(app_id, page-1, member_id=long(member_id))

    # 상품 아이디로 검색
    elif product_id:
        total, payments = models.payments(app_id, page-1, product_id=long(product_id))

    # 총 결제정보
    else:
        total, payments = models.payments(app_id, page-1)

    pagination = make_pagination(page, total, 'payments')
    return render_template('apps/payments.html',
                           app_id = app_id,
                           total = total,
                           payments = payments,
                           pagination = pagination)


@view.route('/<int:app_id>/payments/<int:payment_id>')
@login_required
def payments_detail(app_id, payment_id):
    payment = models.payments_detail(app_id, payment_id)
    if not payment:
        return abort(404)

    return render_template('apps/payments_detail.html',
                           payment = payment)



@view.route('/<int:app_id>/members', defaults={'page':1})
@view.route('/<int:app_id>/members/page=<int:page>')
@login_required
def members(app_id, page):
    # 검색 조건 가져오기
    member_id = request.args.get('member_id', None)
    facebook_id = request.args.get('facebook_id', None)

    # 멤버 아이디로 검색
    if member_id:
        total, members = models.members(app_id, page-1, member_id=long(member_id))

    # 페이스북 아이디로 검색
    elif facebook_id:
        total, members = models.members(app_id, page-1, facebook_id=long(facebook_id))

    # 총 멤버정보
    else:
        total, members = models.members(app_id, page-1)

    pagination = make_pagination(page, total, 'members')
    return render_template('apps/members.html',
                           app_id = app_id,
                           total = total,
                           members = members,
                           pagination = pagination)


@view.route('/<int:app_id>/members/<int:member_id>')
@login_required
def members_detail(app_id, member_id):
    member = models.members_detail(app_id, member_id)
    if not member:
        abort(404)

    return render_template('apps/members_detail.html',
                           app_id = app_id,
                           member = member)


@view.route('/<int:app_id>/members/<int:member_id>/history')
@login_required
def members_history(app_id, member_id):
    access, payment, push = models.members_history(app_id, member_id)
    return render_template('apps/members_history.html',
                           app_id = app_id,
                           member_id = member_id,
                           access = access,
                           payment = payment,
                           push = push)

MemberShip/web/admin/app/views/log.py
# -*- coding:utf-8 -*-

from flask import Blueprint
from flask import render_template
from flask import abort
from flask import request
from flask import redirect
from flask import url_for

from flask.ext.login import login_required
from flask.ext.babel import gettext

from config import MONGODB_HOST as HOST
from config import MONGODB_PORT as PORT
from config import MONGODB_DB as DB
from config import PER_PAGE

from mongoengine import Document
from mongoengine import IntField
from mongoengine import StringField
from mongoengine import DateTimeField

from app import forms
from app import helpers

from util import make_pagination

import re
import pymongo
import datetime

view = Blueprint('log', __name__, 
                 template_folder='../templates')


@view.route('/collections')
@login_required
def collections():
    db = connect_db()

    collections = []
    for col in db.collection_names():
        if col == 'system.indexes': continue
        try:
            #col = int(col)
            collections.append(col)
        except ValueError:
            pass

    collections.sort()
    return render_template('log/collections.html', 
                           collections = collections)


@view.route('/collection/<collection>', methods=['GET'])
@login_required
def collection(collection):
    db = connect_db()
    doc = db[collection]

    pid = request.args.get('pid', None)
    level = request.args.get('level', None)
    name = request.args.get('name', None)
    find = request.args.get('find', None)
    page = int(request.args.get('page', 1))

    search_options = []
    if pid: search_options.append({'process': int(pid)})
    if level: search_options.append({'levelname': level})
    if name: search_options.append({'name': name})
    if find:
        find_search = re.compile(".*"+find+".*", re.IGNORECASE)
        search_options.append({'msg': find_search})

    if len(search_options) > 1:
        search = { "$and": search_options }
    elif len(search_options) == 1:
        search = search_options[0]
    else:
        search = {}

    total = doc.find(search).count()
    pagination = make_pagination(page, total, 'records')

    results = doc.find(search).sort("time", pymongo.DESCENDING).skip((page-1) * PER_PAGE).limit(PER_PAGE)

    url = request.path + "?"
    if pid: url += "pid=%s&" % pid
    if level: url += "level=%s&" % level
    if name: url += "name=%s&" % name
    if find: url += "find=%s&" % find

    records = []
    for r in results:
        try:
            r['tags']
        except KeyError:
            r['tags'] = ''

        records.append({
          'level': r['levelname'],
          'time': r['time'],
          'pid': r['process'],
          'message': r['msg'],
          'host': r['host'],
          'pathname': r['pathname'],
          'lineno': r['lineno'],
          'name': r['name'],
        })

    return render_template('log/list.html',
                           uri = request.path,
                           url = url,
                           pagination = pagination,
                           collection = collection,
                           records = records,
                           time = dispTime,
                           pid = pid,
                           level = level,
                           name = name,
                           find = find)



@view.route('/indexed')
@login_required
def indexed():
    db = connect_db()

    for col in db.collection_names():
        if col == 'system.indexes': continue
        try:
            #if col.isdigit():
            db[col].ensure_index("logging_time")
        except ValueError:
            pass

    return redirect(url_for('log.collections'))


@view.route('/config')
@login_required
def config():
    db = connect_db()

    collections = []
    for col in db.collection_names():
        if col == 'system.indexes': continue
        try:
            info = db.command('collstats', col)
            collections.append({
                 #'name': int(col),
                 'name': col,
                 'count': info['count'],
                 'ns': info['ns'],
                 'size': int(info['storageSize'])
            })
        except ValueError:
            pass

    collections.sort(key=lambda k: k['name'])
    return render_template('log/config.html',
                           collections = collections)


@view.route('/config/<collection>', methods=['POST', 'GET'])
@login_required
def config_edit(collection):
    db = connect_db()
    form = forms.LogConfigEditForm()
    if form.validate_on_submit():
        # 새롭게 설정된 크기로 변경함
        try:
            db.command('convertToCapped', 
                       collection, 
                       size = int(form.value.data))
        except ValueError:
            pass
        return redirect(url_for('log.config'))
    else:
        if collection.isdigit() == False:
            return redirect(url_for('log.config'))

        # 현재 컬랙션의 크기를 보여줌
        try:
            info = db.command('collstats', collection)
            form.value.data = info['storageSize']
        except ValueError:
            pass

    return render_template('log/config_edit.html',
                           form = form,
                           collection = collection,
                           h = helpers)



@view.route('/delete/<collection>', methods=['POST'])
@login_required
def delete(collection):
    db = connect_db()
    try:
        db[collection].drop()
    except ValueError:
        pass
    return redirect(url_for('log.config'))




def dispTime(time):
    return datetime.datetime.strptime(time, "%Y%m%dT%H%M%S.%f")


def connect_db():
    mongo = pymongo.Connection(HOST, PORT)
    db = mongo[DB]
    return db


class Log(Document):
    service_id = IntField(required=True)
    pid = IntField(required=True)
    service_name = StringField(required=True)
    service_port = IntField(required=True)
    ip = StringField(required=True)
    logging_time = DateTimeField(required=True)
    level = IntField(required=True)
    time = DateTimeField(required=True)
    filename = StringField(required=True)
    line = IntField(required=True)
    logger = StringField()
    tags = StringField()
    message = StringField()

MemberShip/web/admin/app/views/monitor.py
# -*- coding:utf-8 -*-

from flask import Blueprint
from flask import render_template
from flask import abort
from flask import redirect
from flask import request

from flask.ext.login import login_required
from flask.ext.babel import gettext

from app import models
from app import admin_permission

view = Blueprint('monitor', __name__, 
                 template_folder='../templates')


@view.route('/process')
@login_required
def process():
    memberships = models.get_memberships()
    pushs = models.get_pushs()
    monitor = models.get_monitor()
    members = models.get_members()
    return render_template('monitor/process.html',
                           memberships = memberships,
                           pushs = pushs,
                           monitor = monitor,
                           members = members)


@view.route('/push')
@login_required
def push():
    push_list = models.push_list()
    return render_template('monitor/push.html',
                           push_list = push_list)


@view.route('/cache')
@login_required
def cache():
    pass



@view.route('/reload')
@login_required
def reload():
    results = models.reload()
    return render_template('monitor/reload.html',
                           results = results)

MemberShip/web/admin/app/templates/_formhelpers.html
{% macro render_field(field) %}
<dt>{{ field.label }}</dt>
<dd>
{{ field(**kwargs)|safe }}
{% if field.errors %}
<ul clsss="errors">
  {% for error in field.errors %}
  <li>{{ error }}</li>
  {% endfor %}
</ul>
{% endif %}
</dt>
{% endmacro %}

MemberShip/web/admin/app/templates/index.html
{% set title = _("Admin Tool") %}

{% extends "layout.html" %}

{% block body %}

<div class="page-header">
  <h1>{{_("MemberShip")}} {{_("Admin Tool")}}</small> </h1>
</div>

<center><img src="/static/imgs/img_logo.png" alt="logo"></center>

{% endblock %}

MemberShip/web/admin/app/templates/layout.html
<html>
<head>
  <meta http-equiv="Pragma" content="no-cache">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{{_("MemberShip")}} {{_("Admin Tool")}}</title>
<link rel="shortcut icon" href="/static/imgs/favicon.ico">
<link rel="stylesheet" href="/static/font-awesome/css/font-awesome.min.css">
<link href="/static/css/admin.css" rel="stylesheet" type="text/css">
<link href="/static/css/pagination.css" rel="stylesheet" type="text/css">
<link href="/static/css/sb-admin.css" rel="stylesheet">
<link href="/static/bootstrap/css/bootstrap.css" rel="stylesheet">
<link href="/static/bootstrap/css/bootstrap-responsive.css" rel="stylesheet">
<link href="/static/select2/select2.css" rel="stylesheet">
{% block extra_head %}{% endblock %}
</head>

<body>
  <div class="container">
    <div class="navbar">
      <div class="navbar-inner">
        <span class="brand"><a href="/">{{_("MemberShip")}} KJS</a></span>
        <ul class="nav">

          <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="javascript:void(0)">{{ _('OPERATE') }}<b class="caret"></b></a>
            <ul class="dropdown-menu">
          		<li><a href="{{ url_for('operate.admin') }}">{{ _('ADMIN') }}</a></li>
            </ul>
          </li>

          <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="javascript:void(0)">{{ _('APPS') }}<b class="caret"></b></a>
            <ul class="dropdown-menu">
          		<li><a href="{{ url_for('apps.apps') }}">{{ _('APPS') }}</a></li>
            </ul>
          </li>

          <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="javascript:void(0)">{{ _('LOG') }}<b class="caret"></b></a>
            <ul class="dropdown-menu">
          		<li><a href="{{ url_for('log.collections') }}">{{ _('COLLECTIONS') }}</a></li>
          		<li><a href="{{ url_for('log.config') }}">{{ _('CONFIG') }}</a></li>
          		<li><a href="{{ url_for('log.indexed') }}">{{ _('INDEXED') }}</a></li>
            </ul>
          </li>

          <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="javascript:void(0)">{{ _('MONITOR') }}<b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><a href="{{ url_for('monitor.process') }}">{{ _('PROCESS') }}</a></li>
              <li><a href="{{ url_for('monitor.push') }}">{{ _('PUSH') }}</a></li>
              <li><a href="{{ url_for('monitor.cache') }}">{{ _('CACHE') }}</a></li>
              <li><a href="{{ url_for('monitor.reload') }}">{{ _('RELOAD') }}</a></li>
            </ul>
          </li>

          <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="javascript:void(0)">{{ _('LANGUAGE') }}<b class="caret"></b></a>
            <ul class="dropdown-menu">
          		<li><a href="{{ url_for('lang', language='ko') }}">{{ _('KOREAN') }}</a></li>
          		<li><a href="{{ url_for('lang', language='en') }}">{{ _('ENGLISH') }}</a></li>
          		<li><a href="{{ url_for('lang', language='zh') }}">{{ _('TAIWAN') }}</a></li>
            </ul>
          </li>

				</ul>
        <ul class="nav pull-right">
          <li>
            <a href="{{ url_for('sitemap') }}">{{ _('SITEMAP') }}</a>
          </li>
          <li>
            <a href="{{ url_for('index.logout') }}">{{ _('LOGOUT') }}</a>
          </li>
        </ul>
      </div>
    </div>
  </div>

<div class="container">

{% block body %} {% endblock %}

</div>

<script src="/static/js/jquery-1.8.3.min.js" type="text/javascript"></script>
<script src="/static/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
<script src="/static/select2/select2.min.js" type="text/javascript"></script>
<script src="/static/js/tablesorter/jquery.tablesorter.js"></script>
<script src="/static/js/tablesorter/tables.js"></script>

{% block script %}
{% endblock %}

</body>
</html>

MemberShip/web/admin/app/templates/lib.html
{# ---------------------- Pager -------------------------- #}
{% macro pager(page, pages, generator) -%}
{% if pages > 1 %}
<div class="pagination">
    <ul>
    {% set min = page - 3 %}
    {% set max = page + 3 + 1 %}

    {% if min < 0 %}
        {% set max = max - min %}
    {% endif %}
    {% if max >= pages %}
        {% set min = min - max + pages %}
    {% endif %}

    {% if min < 0 %}
        {% set min = 0 %}
    {% endif %}
    {% if max >= pages %}
        {% set max = pages %}
    {% endif %}

    {% if min > 0 %}
    <li>
        <a href="{{ generator(0) }}">&laquo;</a>
    </li>
    {% else %}
    <li class="disabled">
        <a href="javascript:void(0)">&laquo;</a>
    </li>
    {% endif %}
    {% if page > 0 %}
    <li>
        <a href="{{ generator(page-1) }}">&lt;</a>
    </li>
    {% else %}
    <li class="disabled">
        <a href="javascript:void(0)">&lt;</a>
    </li>
    {% endif %}

    {% for p in range(min, max) %}
    {% if page == p %}
    <li class="active">
        <a href="javascript:void(0)">{{ p + 1 }}</a>
    </li>
    {% else %}
    <li>
        <a href="{{ generator(p) }}">{{ p + 1 }}</a>
    </li>
    {% endif %}
    {% endfor %}

    {% if page + 1 < pages %}
    <li>
        <a href="{{ generator(page + 1) }}">&gt;</a>
    </li>
    {% else %}
    <li class="disabled">
        <a href="javascript:void(0)">&gt;</a>
    </li>
    {% endif %}
    {% if max < pages %}
    <li>
        <a href="{{ generator(pages - 1) }}">&raquo;</a>
    </li>
    {% else %}
    <li class="disabled">
        <a href="javascript:void(0)">&raquo;</a>
    </li>
    {% endif %}
    </ul>
</div>
{% endif %}
{%- endmacro %}

{# ---------------------- Forms -------------------------- #}
{% macro render_field(form, field, set_focus=False, kwargs={}) %}
  <div class="control-group{{ ' error' if field.errors }}">
    <div class="control-label">
      {{ field.label.text }}
      {% if h.is_required_form_field(field) %}
        <strong style="color: red">&#42;</strong>
      {% else %}
        &nbsp;
      {% endif %}
    </div>
    <div class="controls">
    <div>
      {% if set_focus %}
				{% if field.readonly %}
      		{{ field(autofocus='autofocus', readonly='readonly', **kwargs)|safe }}
				{% else %}
      		{{ field(autofocus='autofocus', **kwargs)|safe }}
				{% endif %}
      {% else %}
				{% if field.readonly %}
      		{{ field(readonly='readonly', **kwargs)|safe }}
				{% else %}
      		{{ field(**kwargs)|safe }}
				{% endif %}
      {% endif %}
    </div>
    {% if field.description %}
    <p class="help-block">{{ field.description }}</p>
    {% endif %}
    {% if field.errors %}
      <ul class="input-errors">
      {% for e in field.errors if e is string %}
        <li>{{ e }}</li>
      {% endfor %}
      </ul>
    {% endif %}
    </div>
  </div>
{% endmacro %}

{% macro render_form_fields(form, set_focus=True, widget_args={}) %}
    {{ form.hidden_tag() if form.hidden_tag is defined }}

    {% for f in form if f.type != 'HiddenField' and f.type != 'CSRFTokenField' %}
      {% set kwargs = widget_args.get(f.name, {}) %}
      {{ render_field(form, f, not loop.index0 and set_focus, kwargs) }}
    {% endfor %}
{% endmacro %}

{% macro form_tag() %}
    <form action="" method="POST" class="form-horizontal" enctype="multipart/form-data">
      <fieldset>
        {{ caller() }}
      </fieldset>
    </form>
{% endmacro %}

{% macro render_form_buttons(cancel_url=None, extra=None) %}
    <div class="control-group">
      <div class="controls">
        <input type="submit" class="btn btn-primary btn-large" value="Submit" />
        {% if extra %}
        {{ extra }}
        {% endif %}
        {% if cancel_url %}
        <a href="{{ cancel_url }}" class="btn btn-large">Cancel</a>
        {% endif %}
      </div>
    </div>
{% endmacro %}

{% macro render_form(form, cancel_url, extra=None, widget_args={}) -%}
    {% call form_tag() %}
        {{ render_form_fields(form, widget_args) }}
        {{ render_form_buttons(cancel_url, extra) }}
    {% endcall %}
{% endmacro %}

MemberShip/web/admin/app/templates/login.html
{% import 'lib.html' as lib with context %}


{% block extra_head %}
<title>{{ _("MemberShip") }} {{_("Admin Tool") }}</title>
<link href="/static/bootstrap/css/bootstrap.css" rel="stylesheet">
<link href="/static/bootstrap/css/bootstrap-responsive.css" rel="stylesheet">
    <style type="text/css">
      body {
        padding-top: 40px;
        padding-bottom: 40px;
        background-color: #f5f5f5;
      }

      .form-signin {
        max-width: 300px;
        padding: 19px 29px 29px;
        margin: 0 auto 20px;
        background-color: #fff;
        border: 1px solid #e5e5e5;
        -webkit-border-radius: 5px;
           -moz-border-radius: 5px;
                border-radius: 5px;
        -webkit-box-shadow: 0 1px 2px rgba(0,0,0,.05);
           -moz-box-shadow: 0 1px 2px rgba(0,0,0,.05);
                box-shadow: 0 1px 2px rgba(0,0,0,.05);
      }
      .form-signin .form-signin-heading,
      .form-signin .checkbox {
        margin-bottom: 10px;
      }
      .form-signin input[type="text"],
      .form-signin input[type="password"] {
        font-size: 16px;
        height: auto;
        margin-bottom: 15px;
        padding: 7px 9px;
      }

    </style>
{% endblock %}

{% block body %}

<div class="container" align="center">

<div class="page-header">
  <h1>{{ _("MemberShip") }} {{_("Admin Tool") }}</h1>
</div>

	<!-- login form -->
{% call lib.form_tag() %}
	{{ lib.render_form_fields(form) }}
	{{ lib.render_form_buttons() }}
{% endcall %}

<p>이 사이트는 멤버쉽 서비스를 위한 도구입니다.</p>
<p><b>허가받지 않은 사용자는 접근하지 마십시요.</b></p>

</div> <!-- /container -->

{% endblock %}



{% block sctip %}
<script src="/static/js/jquery-1.8.3.min.js" type="text/javascript"></script>
<script src="/static/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
<script src="/static/js/form.js"></script>
{% endblock %}

</html>

MemberShip/web/admin/app/templates/sitemap.html
{% extends "layout.html" %}

{% block body %}

<div class="page-header">
	<h3>Sitemap</h3>
</div>

{% if rules %}

<div class="table-responsive">
<table class="table table-bordered table-hover table-striped tablesorter">
  <thead>
  <tr>
    <th>{{ _('URL') }} <i class="fa fa-sort"></th>
    <th>{{ _('END POINT') }} <i class="fa fa-sort"></th>
    <th>{{ _('METHODS') }} <i class="fa fa-sort"></th>
    <th>{{ _('DEFAULTS') }}</th>
    <th>{{ _('ARGUMENTS') }}</th>
  </tr>
  </thead>

  <tbody>
  {% for rule in rules %}
  <tr>
    <td>{{ rule }}</td>
    <td>{{ rule.endpoint }}</td>
    <td>{{ rule.methods }}</td>
    <td>{{ rule.defaults }}</td>
    <td>{{ rule.arguments }}</td>
  </tr>
  {% endfor %}
  </tbody>
</table>
</div>

{% else %}

<p>{{ _('The information does not exist') }}</p>

{% endif %}

{% endblock %}