MemberShip/deploy/qa/web/admin/app/views/log.py
# -*- coding:utf-8 -*-

from flask import Blueprint
from flask import render_template
from flask import abort
from flask import request
from flask import redirect
from flask import url_for

from flask.ext.login import login_required
from flask.ext.babel import gettext

from config import MONGODB_HOST as HOST
from config import MONGODB_PORT as PORT
from config import MONGODB_DB as DB
from config import PER_PAGE

from mongoengine import Document
from mongoengine import IntField
from mongoengine import StringField
from mongoengine import DateTimeField

from app import forms
from app import helpers

from util import make_pagination

import re
import pymongo
import datetime

view = Blueprint('log', __name__, 
                 template_folder='../templates')


@view.route('/collections')
@login_required
def collections():
    db = connect_db()

    collections = []
    for col in db.collection_names():
        if col == 'system.indexes': continue
        try:
            #col = int(col)
            collections.append(col)
        except ValueError:
            pass

    collections.sort()
    return render_template('log/collections.html', 
                           collections = collections)


@view.route('/collection/<collection>', methods=['GET'])
@login_required
def collection(collection):
    db = connect_db()
    doc = db[collection]

    pid = request.args.get('pid', None)
    level = request.args.get('level', None)
    name = request.args.get('name', None)
    find = request.args.get('find', None)
    page = int(request.args.get('page', 1))

    search_options = []
    if pid: search_options.append({'process': int(pid)})
    if level: search_options.append({'levelname': level})
    if name: search_options.append({'name': name})
    if find:
        find_search = re.compile(".*"+find+".*", re.IGNORECASE)
        search_options.append({'msg': find_search})

    if len(search_options) > 1:
        search = { "$and": search_options }
    elif len(search_options) == 1:
        search = search_options[0]
    else:
        search = {}

    total = doc.find(search).count()
    pagination = make_pagination(page, total, 'records')

    results = doc.find(search).sort("time", pymongo.DESCENDING).skip((page-1) * PER_PAGE).limit(PER_PAGE)

    url = request.path + "?"
    if pid: url += "pid=%s&" % pid
    if level: url += "level=%s&" % level
    if name: url += "name=%s&" % name
    if find: url += "find=%s&" % find

    records = []
    for r in results:
        try:
            r['tags']
        except KeyError:
            r['tags'] = ''

        records.append({
          'level': r['levelname'],
          'time': r['time'],
          'pid': r['process'],
          'message': r['msg'],
          'host': r['host'],
          'pathname': r['pathname'],
          'lineno': r['lineno'],
          'name': r['name'],
        })

    return render_template('log/list.html',
                           uri = request.path,
                           url = url,
                           pagination = pagination,
                           collection = collection,
                           records = records,
                           time = dispTime,
                           pid = pid,
                           level = level,
                           name = name,
                           find = find)



@view.route('/indexed')
@login_required
def indexed():
    db = connect_db()

    for col in db.collection_names():
        if col == 'system.indexes': continue
        try:
            #if col.isdigit():
            db[col].ensure_index("logging_time")
        except ValueError:
            pass

    return redirect(url_for('log.collections'))


@view.route('/config')
@login_required
def config():
    db = connect_db()

    collections = []
    for col in db.collection_names():
        if col == 'system.indexes': continue
        try:
            info = db.command('collstats', col)
            collections.append({
                 #'name': int(col),
                 'name': col,
                 'count': info['count'],
                 'ns': info['ns'],
                 'size': int(info['storageSize'])
            })
        except ValueError:
            pass

    collections.sort(key=lambda k: k['name'])
    return render_template('log/config.html',
                           collections = collections)


@view.route('/config/<collection>', methods=['POST', 'GET'])
@login_required
def config_edit(collection):
    db = connect_db()
    form = forms.LogConfigEditForm()
    if form.validate_on_submit():
        # 새롭게 설정된 크기로 변경함
        try:
            db.command('convertToCapped', 
                       collection, 
                       size = int(form.value.data))
        except ValueError:
            pass
        return redirect(url_for('log.config'))
    else:
        if collection.isdigit() == False:
            return redirect(url_for('log.config'))

        # 현재 컬랙션의 크기를 보여줌
        try:
            info = db.command('collstats', collection)
            form.value.data = info['storageSize']
        except ValueError:
            pass

    return render_template('log/config_edit.html',
                           form = form,
                           collection = collection,
                           h = helpers)



@view.route('/delete/<collection>', methods=['POST'])
@login_required
def delete(collection):
    db = connect_db()
    try:
        db[collection].drop()
    except ValueError:
        pass
    return redirect(url_for('log.config'))




def dispTime(time):
    return datetime.datetime.strptime(time, "%Y%m%dT%H%M%S.%f")


def connect_db():
    mongo = pymongo.Connection(HOST, PORT)
    db = mongo[DB]
    return db


class Log(Document):
    service_id = IntField(required=True)
    pid = IntField(required=True)
    service_name = StringField(required=True)
    service_port = IntField(required=True)
    ip = StringField(required=True)
    logging_time = DateTimeField(required=True)
    level = IntField(required=True)
    time = DateTimeField(required=True)
    filename = StringField(required=True)
    line = IntField(required=True)
    logger = StringField()
    tags = StringField()
    message = StringField()

MemberShip/deploy/qa/web/admin/app/templates/log/collections.html
{% extends "layout.html" %}

{% block body %}


<div class="page-header">
	<h3>로그 서비스목록</h3>
</div>

{% if collections %}

<div class="table-responsive">
<table class="table table-bordered table-hover table-striped tablesorter"> 
  <thead>
    <tr>
      <th>서비스 번호 <i class="fa fa-sort"></th>
      <th>이름</th>
    </tr>
  </thead>

{%for col in collections %}
  <tr>
    <td><a href="/log/collection/{{ col }}">{{ col }}</a></td>
    <td>서비스 #{{ col }} 의 로그 내용 </td>
  </tr>
{% endfor %}
 
</table>
</div>

{% else %}
<p>검색할 로그가 존재하지 않습니다.</p>
{% endif %}

{% endblock %}

MemberShip/deploy/qa/web/admin/app/templates/log/config.html
{% extends "layout.html" %}

{% block body %}


<div class="page-header">
	<h3>로그 서비스설정</h3>
</div>

{% if collections %}

<div class="table-responsive">
<table class="table table-bordered table-hover table-striped tablesorter"> 
  <thead>
    <tr>
			<th class="span1">&nbsp;</th>
      <th>테이블명 <i class="fa fa-sort"></th>
      <th>컬럼수 <i class="fa fa-sort"></th>
      <th>용량(B) <i class="fa fa-sort"></th>
    </tr>
  </thead>

{%for col in collections %}
  <tr>
    <td>
			<a href="{{ url_for('log.config_edit', collection = col.name) }}">
				<i class="icon-pencil"></i>
			</a>
			<form class="icon" method="POST" action="{{ url_for('log.delete', collection = col.name) }}">
      <button onclick="return confirm('이 테이블을 삭제하시겠습니까?');">
        <i class="icon-remove"></i>
      </button>
    	</form>
		</td>
		<td>{{ col.name }}</td>
    <td>{{ col.count }}</td>
    <td>{{ col.size }}</td>
  </tr>
{% endfor %}
 
</table>
</div>

{% else %}
<p>설정할 로그 테이블 정보가 존재하지 않습니다.</p>
{% endif %}

{% endblock %}

MemberShip/deploy/qa/web/admin/app/templates/log/config_edit.html
{% extends "layout.html" %}
{% import 'lib.html' as lib with context %}


{% block body %}

<div class="page-header">
	<h3>서비스 {{ collection }} 설정 변경(단위. Byte)</h3>
</div>


{% call lib.form_tag() %}
  {{ lib.render_form_fields(form) }}
  {{ lib.render_form_buttons(url_for("log.collections")) }}
{% endcall %}

{% endblock %}

{% block script %}
<script src="/static/js/form.js"></script>
{% endblock %}

MemberShip/deploy/qa/web/admin/app/templates/log/list.html
{% extends "layout.html" %}

{% block extra_head %}
<meta http-equiv="Pragma" content="no-cache">
<link href="/static/css/log.css" rel="stylesheet" type="text/css">
{% endblock %}

{% block body %}

<div class="page-header">
  <h3>서비스 #{{ collection }} 로그정보</h3>
</div>


{%if records %}

		<form role="form">
      <div class="form-group">
        <input type="text" class="form-control" name="find" placeholder="검색어"/>
      </div>
      <button type="submit" class="btn btn-default">검색</button>
    </form>

	{{ pagination.links|safe }}

    <table border="1" id="log_table">
        <tr>
            <th>Time</th>
            <th>Pid</th>
            <th>Level</th>
            <th>Message</th>
            <th>Host</th>
            <th>Where</th>
            <th>Name</th>
        </tr>
    {%for r in records %}
        <tr class="{{ r.level }}{{ loop.cycle('', '-alt') }}">
            <td>{{ r.time }}</td>
            <td><a href="{{uri}}?pid={{ r.pid }}">{{ r.pid }}</a></td>
            <td><a href="{{uri}}?level={{ r.level }}">{{ r.level }}</a></td>
            <td style="text-align:left;">
                <pre>{{ r.message.replace("\n", "<br>")|safe }}</pre>
            </td>
            <td>{{ r.host }}</td>
            <td width=15% style="text-align:left;word-break:break-all">
                {{ r.pathname }}:{{ r.lineno }}
            </td>
            <td>
                <a href="{{uri}}?name={{ r.name }}">{{ r.name }}</a>
            </td>
        </tr>
    {% endfor %}
    </table>
	{{ pagination.links|safe }}

{% else %}
    <p>No such entry found.</p>
{% endif %}

{% endblock %}